console:
  deploymentConfigs:
    - metadata:
        name: "{{.ApplicationName}}-rhpamcentr"
      spec:
        template:
          metadata:
            name: "{{.ApplicationName}}-rhpamcentr"
          spec:
            containers:
            - name: "{{.ApplicationName}}-rhpamcentr"
              env:
                - name: KIE_ADMIN_PWD
                  value: RedHat
                - name: KIE_SERVER_CONTROLLER_PWD
                  value: RedHat
                - name: KIE_SERVER_PWD
                  value: RedHat
                - name: KIE_MAVEN_USER
                  value: mavenUser
                - name: KIE_MAVEN_PWD
                  value: RedHat
  routes:
    - metadata:
        labels:
          app: "{{.ApplicationName}}"
          service: "{{.ApplicationName}}-rhpamcentr"
        name: "{{.ApplicationName}}-rhpamcentr"
      spec:
        port:
          targetPort: http
        to:
          name: "{{.ApplicationName}}-rhpamcentr"
    - metadata:
        name: "{{.ApplicationName}}-rhpamcentr-https"
        annotations:
          delete: "true"
  services:
    - spec:
        ports:
          - name: git-ssh
            port: 8001
            targetPort: 8001
      metadata:
        name: "{{.ApplicationName}}-rhpamcentr"
    - metadata:
        name: "{{.ApplicationName}}-rhpamcentr-ping"
        annotations:
          delete: "true"
  persistentVolumeClaims:
    - metadata:
        name: "{{.ApplicationName}}-rhpamcentr-claim"
        annotations:
          delete: "true"

## KIE Servers BEGIN
servers:
## RANGE BEGINS
{{ range $index, $Map := .ServerCount }}
  - deploymentConfigs:
      - metadata:
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-kieserver-{{$index}}"
          name: "{{.ApplicationName}}-kieserver-{{$index}}"
        spec:
          replicas: 1
          template:
            metadata:
              name: "{{.ApplicationName}}-kieserver-{{$index}}"
            spec:
              containers:
              - name: "{{.ApplicationName}}-kieserver-{{$index}}"
                env:
                - name: KIE_ADMIN_PWD
                  value: RedHat
                - name: KIE_SERVER_CONTROLLER_PWD
                  value: RedHat
                - name: KIE_SERVER_PWD
                  value: RedHat
                - name: EXECUTION_SERVER_ROUTE_NAME
                  value: "{{.ApplicationName}}-kieserver-{{$index}}"
                - name: RHPAMCENTR_MAVEN_REPO_USERNAME
                  value: mavenUser
                - name: RHPAMCENTR_MAVEN_REPO_PASSWORD
                  value: RedHat
                - name: RHPAMCENTR_MAVEN_REPO_SERVICE
                  value: "{{.ApplicationName}}-rhpamcentr"
    services:
      - spec:
          ports:
            - name: http
              port: 8080
              targetPort: 8080
        metadata:
          name: "{{.ApplicationName}}-kieserver-{{$index}}"
      - spec:
        metadata:
          name: "{{.ApplicationName}}-kieserver-{{$index}}-ping"
          annotations:
            delete: "true"
    routes:
      - metadata:
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-kieserver-{{$index}}"
          name: "{{.ApplicationName}}-kieserver-{{$index}}"
        spec:
          port:
            targetPort: http
          to:
            name: "{{.ApplicationName}}-kieserver-{{$index}}"
    persistentVolumeClaims:
      - metadata:
          name: "{{.ApplicationName}}-h2-claim-{{$index}}"
          annotations:
            delete: "true"
{{end}}
## RANGE ends
## KIE Servers END
