apiVersion: app.kiegroup.org/v1
kind: KieApp
metadata:
  name: common-config
spec:
  environment: rhpam-trial
  commonConfig:
    # By default is the cr.Name
    applicationName: other
    adminPassword: example
    imageTag: 1.0-stage
    mavenRepo: INTERNAL
