apiVersion: apps/v1
kind: Deployment
metadata:
  name: kie-cloud-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kie-cloud-operator
  template:
    metadata:
      labels:
        name: kie-cloud-operator
    spec:
      containers:
        - name: kie-cloud-operator
          image: quay.io/kiegroup/kie-cloud-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - kie-cloud-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "kie-cloud-operator"
