#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: kie-cloud-operator

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kie-cloud-operator
rules:
- apiGroups:
  - kiegroup.org
  resources:
  - "*"
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sa-default-kie-cloud-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: kie-cloud-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: sa-default-admin
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  name: admin